# Generated by Django 6.0.3 on 2026-04-19 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_menuitem_image_alter_menuitem_price'),
    ]

    operations = [
        # Rename Item to InventoryItem
        migrations.RenameModel(
            old_name='item',
            new_name='inventoryitem',
        ),
        # Add new fields to Category
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=50, unique=True, null=True),
        ),
        # Rename fields in InventoryItem
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='stock_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='min_stock',
            new_name='reorder_threshold',
        ),
        # Add new fields to InventoryItem
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Create StockTransaction model
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('quantity', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=models.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        # Add new fields to MenuItem
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='linked_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='inventory.inventoryitem'),
        ),
        # Update Recipe model to reference InventoryItem
        migrations.AlterField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(on_delete=models.CASCADE, to='inventory.inventoryitem'),
        ),
        # Update Sale model
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
