# Generated by Django 6.0.3 on 2026-04-19 04:19

from django.db import migrations, models
from django.utils.text import slugify


def populate_category_slugs(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    for category in Category.objects.all():
        base_slug = slugify(category.name)
        slug = base_slug
        counter = 1
        while Category.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        category.slug = slug
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20260419_1219'),
    ]

    operations = [
        migrations.RunPython(populate_category_slugs),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=50, unique=True),
        ),
    ]
