# Generated by Django 6.0.3 on 2026-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_category_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='date',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_threshold',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_used',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
