# Generated by Django 6.0.3 on 2026-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_lowstockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
