# Generated by Django 6.0.3 on 2026-04-29 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_lowstockalert_acknowledged_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_low_stock_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='snoozed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snoozed_low_stock_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
